function batfig(ymatrix1, Y1)
%CREATEFIGURE(ymatrix1, Y1)
%  YMATRIX1:  bar matrix data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 23-Apr-2025 12:04:31

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Activate the left side of the axes
yyaxis(axes1,'left');
% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'BarLayout','stacked','Parent',axes1);
set(bar1(4),'DisplayName','P^t_1','FaceColor',[0 1 1]);
set(bar1(3),'DisplayName','P^t_2','FaceColor',[0 1 0]);
set(bar1(2),'DisplayName','P^t_3','FaceColor',[0 0 1]);
set(bar1(1),'DisplayName','P^t_4','FaceColor',[1 0 1]);

% Create xline
xline(11,'DisplayName','Market Price','Parent',axes1,'LineWidth',2);

% Create xline
xline(14,'Parent',axes1,'LineWidth',2);

% Create xline
xline(18,'Parent',axes1,'LineWidth',2);

% Create xline
xline(21,'Parent',axes1,'LineWidth',2);

% Create ylabel
ylabel('P_{b,ch/dis} (kW)');

% Activate the right side of the axes
yyaxis(axes1,'right');
% Create plot
plot(Y1,'LineWidth',2,'Color',[0 0 0]);

% Create ylabel
ylabel('Market Price ($/MWh)');

% Create xlabel
xlabel('Time (Hour)','FontWeight','bold');

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','Times','FontSize',24,'FontWeight','bold');
% Create legend
legend(axes1,'show');

% Create textbox
annotation(figure1,'textbox',...
    [0.462279293739952 0.522999998807908 0.116372391653304 0.0625000011920932],...
    'String',{'HILF Event'},...
    'FontWeight','bold',...
    'FontSize',24,...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.674157303370749 0.523499998807909 0.116372391653303 0.0625000011920932],...
    'String',{'HILF Event'},...
    'FontWeight','bold',...
    'FontSize',24,...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

